Add HAProxy PROXY header if configured for upstream handlers
mholt/caddy-l4 pull request #21
Opened 2021-04-30 21:25 UTC by mildred

Follows #14
Fixes #13

2021-04-30 21:41 UTC, mildred commented
Just checked it again, working great.

2021-04-30 22:08 UTC, mholt requested changes
Thanks for bringing it back! I think this is pretty good, just a couple nits. What are your thoughts on changing the field type from string to int, since it's just a version number? (I don't feel strongly either way. Why did you choose a string?)

2021-04-30 22:08 UTC, mholt commented on modules/l4proxy/proxy.go
> +	ProxyHeader string `json:"proxy_header,omitempty"`
I actually wonder if this should be an `int` instead, just the version number. Hmm.

2021-05-01 02:55 UTC, lxhao61 commented on modules/l4proxy/proxy.go
> +		return fmt.Errorf("proxy_header: \"%s\" should be empty or one of \"v1\" \"v2\"", h.ProxyHeader)
totally agree！

2021-05-02 21:06 UTC, mildred commented on modules/l4proxy/proxy.go
> +	ProxyHeader string `json:"proxy_header,omitempty"`
No specific reason why the string except empty value is more discoverable, and string is more future-proof.

2021-05-03 02:11 UTC, mholt approved these changes
Cool, thank you! Let's give it a try.

2021-05-03 02:11 UTC, merged