Add support for XMPP
mholt/caddy-l4 pull request #33
Opened 2021-11-05 11:35 UTC by Rijul-A

1. Add generic ALPN matcher, which is used to match `xmpp-client` for XMPP. Let me know if this is better suited elsewhere (like the main Caddy repository).
2. Add XMPP matcher, which is similar to SSH matcher except it looks for the word `jabber` in the [first 50 bytes](https://github.com/yrutschle/sslh/blob/0e118a109c0407e47c8e43e37662df0f6c0367f2/probe.c#L175). 

Use case: Replacement for forwarding Snikket traffic over port 443 to relevant service; documented [here](https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md#sslh) using `sslh`

2021-11-08 18:58 UTC, mholt commented
Hi, thanks for this contribution! I am trying to tag a new release of Caddy but I hope to look at this in the next little while.

2021-11-17 22:45 UTC, mholt requested changes
I like this! The XMPP one is a good fit. I'm trying to decide whether the ALPN matcher is a better fit for Caddy's `caddytls` package directly so that other Caddy sites can use it, or if it should be exclusive to this module. Hmm hmm hmm. Most Caddy apps are using HTTP on top of TLS, since most Caddy users use it for its HTTP server. But then again, there could be value in handling a handshake one way based on ALPN versus another way, since that repo is where the TLS server lives.

Hmm...

I guess we can always start with it here and then move it if we need to (it's harder to go the other way around).

Please use `go fmt` to clean up the code, and ensure the copyright is intact. Thanks!

2021-11-17 22:45 UTC, mholt commented on modules/l4tls/alpn_matcher.go
> +  }
Is this needed? We can probably omit this right?

2021-11-18 17:37 UTC, mholt approved these changes
Neat, thank you so much for contributing this!

2021-11-18 17:37 UTC, merged

2022-10-03 19:41 UTC, Rijul-A commented
I just observed that the SSH matcher must be before the XMPP matcher for the handling to work correctly (matching appears to work fine in either order).

2022-10-04 17:52 UTC, mholt commented
@Rijul-A I wonder if that is due/related to https://github.com/mholt/caddy-l4/pull/72.